### ISSUE TITLE
can not run the sample.py

### ISSUE THREAD

**Issue by small-jian-house** [luost26/3D-Generative-SBDD#10]
Hi
excuse me, I can't run the script sample.py
the error is No such file or directory: './data/crossdocked_pocket10_name2id.pt', i have no idea, could you tell how can i solve this problem? thank you!

**Comment by luost26** [comment]
Have you downloaded `split_by_name.pt` from [here](https://drive.google.com/drive/folders/1CzwxmTpjbrt83z_wBzcQncq84OVDPurM) and put it into the `data` folder ?

**Comment by small-jian-house** [comment]
yes, I have done that.

**Comment by luost26** [comment]
Are you using the latest version of the code?

The code has been updated several times, it seems that `crossdocked_pocket10_name2id.pt` only appears in older versions.

**Comment by small-jian-house** [comment]
I checked, the version of the code is lastest, 
I found the line 167 of the sample.py calls the get_data function，eventually the code on line 19 of utils/datasets/pl.py is called. And the content is self.name2id_path = os.path.join(os.path.dirname(self.raw_path), os.path.basename(self.raw_path) + '_name2id.pt'),

**Comment by small-jian-house** [comment]
I've solved it，thank you

**Comment by luost26** [comment]
That's great! I wonder what happened. Can you share with us? Thanks!

**Comment by small-jian-house** [comment]
ok, I guess that I didn't download the crossdocked_pocket10.tar.gz at first, but I ran the sample.py. Then the crossdocked_pocket10_processed.lmdb was created, but the crossdocked_pocket10_name2id.pt was not created.  see code.
`        self.processed_path = os.path.join(os.path.dirname(self.raw_path), os.path.basename(self.raw_path) + '_processed.lmdb')
        self.name2id_path = os.path.join(os.path.dirname(self.raw_path), os.path.basename(self.raw_path) + '_name2id.pt')
        self.transform = transform
        self.db = None

        self.keys = None

        if not os.path.exists(self.processed_path):
            self._process()
            self._precompute_name2id()`
The 'lmdb' and 'pt' must be created at the same time, and the 'pt' will not be created when there is 'lmdb' in the data file. Therefore, after extracting the TAR package, this error happened.

**Comment by luost26** [comment]
Thank you! This is very helpful!
