### ISSUE TITLE
How to evaluate the model?

### ISSUE THREAD

**Issue by Layne-Huang** [luost26/3D-Generative-SBDD#19]
Sorry to bother you. May I ask you how to evaluate the performance of the model since there is no script for evaluation?

**Comment by luost26** [comment]
https://github.com/luost26/3D-Generative-SBDD/blob/main/utils/docking.py 
provides helper functions to evaluate binding affinities of the generated molecules.

The methods for computing SA, QED scores can be found in previous work.
