### ISSUE TITLE
How to determine if the generated atoms/bonds are aromatic or not?

### ISSUE THREAD

**Issue by mengliu1998** [luost26/3D-Generative-SBDD#2]
Hi @luost26,

Thank you for this interesting work. I have a question about the bond inference process.

After sampling, we have the generated atom types and their positions, and our goal is to infer the bonds among these atoms. In this [line](https://github.com/luost26/3D-Generative-SBDD/blob/6f9c7d92784e58474b9c22a74c8113f0344ca795/utils/reconstruct.py#L99), it seems that we can decide if an added bond should be aromatic or not. For this line, I am confused about what is the `indicator` for test data used in generation. From my understanding, what we have after sampling are generated atom types and their positions. How can we determine if the generated atoms/bonds should be aromatic or not?

Thank you in advance. Any discussions from others are also warmly welcome.

**Comment by luost26** [comment]
Hi,

Thank you for your interest in our project. The indicators predicted by the network are not used in the final version. It's a legacy of previous experiments.

**Comment by mengliu1998** [comment]
Got it. Thank you for the clarification.
