### ISSUE TITLE
Could you share the codes of 'Linker Prediction' parts?

### ISSUE THREAD

**Issue by tbwxmu** [luost26/3D-Generative-SBDD#20]
We replaced the empty ligand_dict with docked fragments in the script 'samples_for_pdb.py',  but the outputs of SDF files do not contain our prepared fragments anymore. It seems your model still starts from scratch not considering the input fragments at all.
```python
# ligand_dict = {
#     'element': torch.empty([0,], dtype=torch.long),
#     'pos': torch.empty([0, 3], dtype=torch.float),

#     'atom_feature': torch.empty([0, 8], dtype=torch.float),
#     'bond_index': torch.empty([2, 0], dtype=torch.long),
#     'bond_type': torch.empty([0,], dtype=torch.long),
# }

path='ZINC_2_frag.sdf'
ligand_dict = parse_sdf_file(path)
ligand_dict=torchify_dict(ligand_dict)
```
Please share your codes or pipeline about the Linker Prediction of your paper.

**Comment by TAEUKHAM** [comment]
I was also wondering about the linker prediction part too

**Comment by TAEUKHAM** [comment]
@tbwxmu Did you solved this issue? I'm still working how to figure out this linker part. Would be so glad if you share the code:)
