### ISSUE TITLE
How to test the program by our own system

### ISSUE THREAD

**Issue by YuxiuLiu** [luost26/3D-Generative-SBDD#5]
Sorry to bother you，I ran the test model successfully and got the smiles structures of generated molecules, however, I have no idea about how to run our own example, though we replace the test system with our own one and I also wonder the meaning of the number in the last part of this list ('YPKA_YERPS_90_433_0/5ce3_B_rec_5ce3_adp_lig_tt_min_0_pocket10.pdb', 'YPKA_YERPS_90_433_0/5ce3_B_rec_5ce3_adp_lig_tt_min_0.sdf', 'YPKA_YERPS_90_433_0/5ce3_B_rec.pdb', 0.552965)

**Comment by luost26** [comment]
Hi! 

We are planning to release a script that can convert other proteins to the model-supported format.

- `YPKA_YERPS_90_433_0/5ce3_B_rec.pdb`: is the path to the target protein's PDB file.
- `YPKA_YERPS_90_433_0/5ce3_B_rec_5ce3_adp_lig_tt_min_0_pocket10.pdb`: is the path to the extracted pocket, a substructure of the protein.
- `YPKA_YERPS_90_433_0/5ce3_B_rec_5ce3_adp_lig_tt_min_0.sdf`: is the path to the reference ligand.

All of them can be found in the unprocessed dataset archive: `crossdocked_pocket10.tar.gz`.

**Comment by YuxiuLiu** [comment]
> Hi!
> 
> We are planning to release a script that can convert other proteins to the model-supported format.
> 
> * `YPKA_YERPS_90_433_0/5ce3_B_rec.pdb`: is the path to the target protein's PDB file.
> * `YPKA_YERPS_90_433_0/5ce3_B_rec_5ce3_adp_lig_tt_min_0_pocket10.pdb`: is the path to the extracted pocket, a substructure of the protein.
> * `YPKA_YERPS_90_433_0/5ce3_B_rec_5ce3_adp_lig_tt_min_0.sdf`: is the path to the reference ligand.
> 
> All of them can be found in the unprocessed dataset archive: `crossdocked_pocket10.tar.gz`.

Sorry to bother you again, what's the meaning of the number 0.552965 in the list?

**Comment by luost26** [comment]
> > Hi!
> > We are planning to release a script that can convert other proteins to the model-supported format.
> > 
> > * `YPKA_YERPS_90_433_0/5ce3_B_rec.pdb`: is the path to the target protein's PDB file.
> > * `YPKA_YERPS_90_433_0/5ce3_B_rec_5ce3_adp_lig_tt_min_0_pocket10.pdb`: is the path to the extracted pocket, a substructure of the protein.
> > * `YPKA_YERPS_90_433_0/5ce3_B_rec_5ce3_adp_lig_tt_min_0.sdf`: is the path to the reference ligand.
> > 
> > All of them can be found in the unprocessed dataset archive: `crossdocked_pocket10.tar.gz`.
> 
> Sorry to bother you again, what's the meaning of the number 0.552965 in the list?

Hi

Can you provide to context of the number `0.552965`? Thanks!

**Comment by luost26** [comment]
Hi,

Now you may use `sample_for_pdb.py` to generate ligands for your proteins. Instructions and examples are in the README.
